// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.
// This is a stub file - run `go generate ./...` to regenerate

package graph

import (
	"github.com/99designs/gqlgen/graphql"
	"github.com/kalyankumar/graphql-product-search/graph/model"
)

// Config is passed to the generated code to configure it
type Config struct {
	Resolvers  ResolverRoot
	Directives DirectiveRoot
	Complexity ComplexityRoot
}

type ResolverRoot interface {
	Mutation() MutationResolver
	Product() ProductResolver
	Query() QueryResolver
	Subscription() SubscriptionResolver
}

type DirectiveRoot struct{}

type ComplexityRoot struct {
	Category struct {
		ID           func(childComplexity int) int
		Name         func(childComplexity int) int
		ProductCount func(childComplexity int) int
		Slug         func(childComplexity int) int
	}

	Mutation struct {
		CreateProduct func(childComplexity int, input model.CreateProductInput) int
		CreateReview  func(childComplexity int, input model.CreateReviewInput) int
		DeleteProduct func(childComplexity int, id string) int
		DeleteReview  func(childComplexity int, id string) int
		UpdateProduct func(childComplexity int, id string, input model.UpdateProductInput) int
	}

	PageInfo struct {
		EndCursor       func(childComplexity int) int
		HasNextPage     func(childComplexity int) int
		HasPreviousPage func(childComplexity int) int
		StartCursor     func(childComplexity int) int
		TotalCount      func(childComplexity int) int
	}

	Product struct {
		Category    func(childComplexity int) int
		CreatedAt   func(childComplexity int) int
		Description func(childComplexity int) int
		ID          func(childComplexity int) int
		ImageURL    func(childComplexity int) int
		Name        func(childComplexity int) int
		Price       func(childComplexity int) int
		Rating      func(childComplexity int) int
		ReviewCount func(childComplexity int) int
		Stock       func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
	}

	ProductConnection struct {
		Edges    func(childComplexity int) int
		PageInfo func(childComplexity int) int
	}

	ProductEdge struct {
		Cursor func(childComplexity int) int
		Node   func(childComplexity int) int
	}

	Query struct {
		Categories        func(childComplexity int) int
		Category          func(childComplexity int, id string) int
		Product           func(childComplexity int, id string) int
		Products          func(childComplexity int, first *int, after *string, last *int, before *string, filter *model.ProductFilterInput, sort *model.ProductSortInput) int
		Reviews           func(childComplexity int, productID string, first *int, after *string) int
		SearchSuggestions func(childComplexity int, query string, limit *int) int
	}

	Review struct {
		Comment   func(childComplexity int) int
		CreatedAt func(childComplexity int) int
		ID        func(childComplexity int) int
		ProductID func(childComplexity int) int
		Rating    func(childComplexity int) int
		UserID    func(childComplexity int) int
		UserName  func(childComplexity int) int
	}

	ReviewConnection struct {
		Edges    func(childComplexity int) int
		PageInfo func(childComplexity int) int
	}

	ReviewEdge struct {
		Cursor func(childComplexity int) int
		Node   func(childComplexity int) int
	}

	Subscription struct {
		ProductUpdated func(childComplexity int, id string) int
		ReviewAdded    func(childComplexity int, productID string) int
	}
}

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		resolvers: cfg.Resolvers,
	}
}

type executableSchema struct {
	resolvers ResolverRoot
}

func (e *executableSchema) Schema() *graphql.Schema {
	return nil // Stub - normally generated
}

func (e *executableSchema) Complexity(typeName, fieldName string, childComplexity int, rawArgs map[string]interface{}) (int, bool) {
	return 0, false // Stub
}

func (e *executableSchema) Exec(ctx interface{}) graphql.ResponseHandler {
	return nil // Stub
}
